### ISSUE TITLE
Nested split layouts do not show scrollbars correctly

### ISSUE THREAD

**Issue by snyholm** [vaadin/vaadin-split-layout#10]
On our demo page https://vaadin.com/elements/-/element/vaadin-split-layout the nested layout demo does not display the top right scrollbars correctly. When minimizing the area so that vertical scrollbars would be needed, a scrollbar with 100% height is showed instead and prevents scrolling. Browser in question is latest chrome on Windows.

Edit: After it was pointed out to me, it seems to be an issue that the scrollbars for the Grid is not shown while the scrollbars for the Split Layout is, which leads me to not being able to scroll the grid without using the scroll wheel while the unnecessary layout scrollbars are shown.

![ss](https://cloud.githubusercontent.com/assets/2834461/18012543/a9e978e2-6bc2-11e6-8aff-186cb1310891.png)

**Comment by Peppe** [comment]
I'm pretty sure the extra scrollbar is an internal Grid problem. In Grid, there is the extra iframe measureobject that sets the height. It has expliciely set 100% height and implicitely set 2px wide borders, which I guess comes from browser defaults. Border width is not explicitely set for this iframe. If I add `border:none` on the iframe, this extra scrollbar dissappears and things work as expected.

![extra-border](https://cloud.githubusercontent.com/assets/525503/18015450/726b0364-6bd0-11e6-8577-0687ab473fab.png)

**Comment by jouni** [comment]
Thanks @Peppe, nice catch, and with a fix even 😃

**Comment by tomivirkki** [comment]
The live site seems to be running an old version of vaadin-grid since this issue was fixed by https://github.com/vaadin/vaadin-grid/commit/e83b607e7237907892a7e10cc7acefa819985584 back in January

The demo source claims to be using the CDN master version of grid but it actually imports vaadin-grid from this bundle: https://vaadin.com/elements-page-1.0-SNAPSHOT/all-the-things.html

**Comment by jouni** [comment]
This issue was moved to vaadin/elements-page#12
