### ISSUE TITLE
Components stay disabled upon right-clicking when resizing

### ISSUE THREAD

**Issue by edler-san** [vaadin/vaadin-split-layout#111]
If you happen to right-click during a resizing operation both the contents of the primary and secondary stay disabled until you refresh the page.

Minimal example to reproduce:

```
SplitLayout layout = new SplitLayout();
layout.setOrientation(Orientation.HORIZONTAL);
layout.addToPrimary(new Label("1"));
layout.addToSecondary(new Button("1"));		
add(layout);

```
Hold the dragger and right-click - you can no longer push the button even if you try to resize again.

**Comment by web-padawan** [comment]
Thanks for the issue. This repo is for the Web Component, and for its Java counterpart we have different repo. I will move it there so that our teammates could handle it appropriately.

**Comment by web-padawan** [comment]
This issue was moved to vaadin/vaadin-split-layout-flow#40
