### ISSUE TITLE
Can't set the splitterposition after moving the splitter manually

### ISSUE THREAD

**Issue by LennartKuell** [vaadin/vaadin-split-layout#126]
I tried to set the position in the code with .setSplitterPosition(90). This works fine, but it won't change the position, if I moved the splitter manually with my mouse before. So once I use the mouse to move the splitter, setSplitterPosition shows no effect anymore.
The reason seems to be, that moving the splitter with the mouse sets the "flex" attribute as style of the children, while setting it with setSplitterPosition sets the "height" attribute. I also tried to remove the flex attribute in the code, but this does not work, because the flex attribute isn't set in the children. I checked this with with splitLayout.getPrimaryComponent().getElement().getStyle().

I tested this with both Firefox and Chromium on LinuxMint and Chromium on Ubuntu.

**Comment by limonte** [comment]
Works fine on the front-end side, see the "Initial Splitter Position
" example here: https://cdn.vaadin.com/vaadin-split-layout/4.1.0/demo/#split-layout-basic-demos

Moving to flow for further investigation...

**Comment by limonte** [comment]
This issue was moved to vaadin/vaadin-split-layout-flow#47
