### ISSUE TITLE
UX testing

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-split-layout#13]
Lightweight hallway testing to verify that users recognize the element as a split handle and that the touch target area is large enough.

**Comment by samiheikki** [comment]
https://docs.google.com/document/d/1V05ySpaLLM73P5qF907jnHJrWo37HPGZ7Cr3EPJgNQY/edit#heading=h.i2seo1qhzao2 UX testing summary

**Comment by samiheikki** [comment]
Issue created: https://github.com/vaadin/vaadin-split-layout/issues/22
Other issue's PR: https://github.com/vaadin/vaadin-split-layout/pull/21
