### ISSUE TITLE
Bug when vaadin split layout horizontal inside vaadin split layout vertical.

### ISSUE THREAD

**Issue by ybarbaria** [vaadin/vaadin-split-layout#14]
When I add vaadin split layout horizontal inside vaadin split vertical, the second split have a style of vertical split. 

 Any solution ?
 
Visible in the attached picture.
![bugsplitvaadin](https://cloud.githubusercontent.com/assets/5574663/19938380/0908d376-a125-11e6-8b40-f392d6324f18.PNG)

**Comment by tomivirkki** [comment]
Hi @ybarbaria 
Thanks for reporting. Created PR https://github.com/vaadin/vaadin-split-layout/pull/15 to fix the issue

**Comment by ybarbaria** [comment]
Hi @tomivirkki! 
Thx for your update !  

This fix is it available ?

**Comment by samiheikki** [comment]
Hi @ybarbaria 

We haven't made a new release after this fix yet, but it is found in the master version. You can bower install master version using `bower install vaadin-split-layout#master`
