### ISSUE TITLE
split layout render issues

### ISSUE THREAD

**Issue by DiegoSanzVi** [vaadin/vaadin-split-layout#153]
It seems that there is a problem of rendering when scrolling.

Here is a project that recreates the issue:
https://github.com/DiegoSanzVi/splitLayoutIssue

To recreate the issue:
1. Resize the Split layout
2. Scroll down and up.

I tried it on Google Chome(last version). It seems to work on Firefox. 

It is not reproducible with pure webcomponents.

![image](https://user-images.githubusercontent.com/40760222/49155821-904ae600-f324-11e8-8a54-e0e1eb6bc554.png)

![image](https://user-images.githubusercontent.com/40760222/49155870-a658a680-f324-11e8-800b-528e6fc6ea51.png)

**Comment by tomivirkki** [comment]
No longer reproducible. I assume it was an issue in Chrome that has now been fixed because even the original example project (Vaadin 11) works fine now. Closing.
