### ISSUE TITLE
There is some event to know when the user release the component after resize ? 

### ISSUE THREAD

**Issue by ybarbaria** [vaadin/vaadin-split-layout#17]
Hello, 

All is in the title of my issue, but for the moment I use the event 'iron-resize' but is emit many times, I need juste one event emit one time at the end. 
It is for resize grid component inside. 

Is it possible to find event like that? 

Thx 

Yvan

**Comment by limonte** [comment]
Hi Yvan,

There's no "end" for resize events. I believe `debounce()` is what you're looking for. This should work for you:

```js
_onIronResize: function() {
  this.debounce('resizeDebounce', function() {
    console.log('Resized');
  }, 1000);
}
```

Read more about debounce function: https://davidwalsh.name/javascript-debounce-function
