### ISSUE TITLE
UX: Increase touch target size for easier drag in mobile

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-split-layout#22]
Discovered in UX testing that touch target size is not big enough. Participants were able to resize only about 50% of the time.

**Comment by Saulis** [comment]
Request from @jouni: make it 44x44px by default, and add a way to customize the size.

**Comment by upstairlounge** [comment]
Tomi says: might be an ios thing, cannot reproduce with Android

**Comment by tomivirkki** [comment]
Increasing the touch target handles the issue quite well. Will be fixed by vaadin/vaadin-split-layout#19
