### ISSUE TITLE
Initial resize event fired before children are attached

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-split-layout#42]
The initial resize event is fired before the child elements are attached. This makes it a tad difficult to layout a child component correctly initially.

```
<!doctype html>
<head>

<script src="bower_components/webcomponentsjs/webcomponents.min.js"></script>
<link rel="import" href="bower_components/vaadin-split-layout/vaadin-split-layout.html">

<body>

<vaadin-split-layout id="split">
<div></div>
<div id="s">Second</div>
</vaadin-split-layout>
<script>
split.addEventListener("iron-resize", function() {
  window.s.innerText = "Available width: "+s.offsetWidth;
});

</script>
```

**Comment by platosha** [comment]
This is not the intended usage. You should listen for `'iron-resize'` in a custom child element to get the resize event for this child. See example jsbin: http://jsbin.com/zidisupagi/edit?html,output

Docs: https://vaadin.com/docs/-/part/elements/vaadin-split-layout/vaadin-split-layout-resize-event.html

**Comment by Artur-** [comment]
How do I do that when the child is not a Polymer element?

**Comment by Artur-** [comment]
The docs say `When the user drags the splitter of the <vaadin-split-layout> element, the element dispatches the iron-resize event. You can subscribe to this event in order to get notified of a split resize.`

This is what the example code above does according to how I interpret it. It also works just fine for all events except for the first one

**Comment by web-padawan** [comment]
The original use case is covered by `splitter-dragend` event added by #97. Closing.
