### ISSUE TITLE
Resizing isn't working with complex content

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-split-layout#50]
If panels contain complex content (e.g. Google Maps iframes), then resizing isn't working properly. 

In case of complex content, it takes more time to rerender panels and if mouse moves faster than rerendering process than resizing stops working.

Live example: https://github.com/vaadin/vaadin-split-layout/pull/49

**Comment by jouni** [comment]
One possible fix is probably to add `pointer-events: none;` to both content slots during resizing.
