### ISSUE TITLE
Installing Polymer 2.0 compatible version

### ISSUE THREAD

**Issue by nicolasr75** [vaadin/vaadin-split-layout#58]
Hello vaadin team! Thanks for the great work!

I would like to test vaadin-split-layout with Polymer 2.0 but I don't understand how to install it. With Polymers own elements I did

`bower install blablabla#2.0-preview`

to get the hybrid versions. But how would I do it for the split layout? I noticed your bower.json does have variant dependencies for 2.0 but when I do

`bower install vaadin-split-layout`

it always wants to resolve the 1.0 deps.

Should I download the github repo and manually place it in my bower_components?
Any help much appreciated.
Nicolas

**Comment by limonte** [comment]
Hello Nicolas,

Yeah, as you noticed we released hybrid element today. However, Polymer 1.x is still default dependency.

To make Polymer 2.x deps installed by default you should add `resolutions` section to `bower.json`:

```js
"resolutions": {
  "polymer": "2.0-preview",
  "webcomponentsjs": "v1"
}
 ```

After this Polymer 2.x deps will be installed automatically and you will see something like this:

```
Please note that,
Resort to using polymer#2.0-preview which resolved to polymer#d46694e5d5

Please note that,
Resort to using webcomponentsjs#v1 which resolved to webcomponentsjs#1.0.0-rc.5
```

**Comment by nicolasr75** [comment]
Thanks for the quick response. I tried what you suggested but bower still complained about unresolvable iron-resizable behavior. I followed bowers wizard to resolve dependencies and this is what my bower.json contains now:

    "resolutions": {
        "polymer": "^2.0.0-rc.2",
        "webcomponentsjs": "1.0.0-rc.5",
        "iron-resizable-behavior": "2.0-preview"
    }

Anyway, I am able to use the split layout now and am excited to see how it will work :-)

**Comment by limonte** [comment]
You're welcome. Thanks for using the `vaadin-split-layout`!
