### ISSUE TITLE
Customizable styles

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-split-layout#6]
Consider to implement customizability for the following:
- splitter style with a mixin
- icon style, icon image, maybe with a light DOM?

Align the default styling with Material Desing / paper-styles.

**Comment by manolo** [comment]
For reference MD specification for splits: https://material.google.com/layout/split-screen.html#
Probably we should math this specification by default

**Comment by platosha** [comment]
Note that the spec says “Android only”.
