### ISSUE TITLE
Change attributes on button-click not working

### ISSUE THREAD

**Issue by SamaneriVimala** [vaadin/vaadin-split-layout#61]
Great webcomponent! I use it for toggling between a view with one or two areas. The only thing that is not working is to change the class of the splitter on button-click. I have two classes, `splitterbar` and `nosplit`. If I show two areas, I want it to have class `splitterbar`, otherwise class `nosplit`. The classes are changed by js perfectly well, but do not filter down into the actual `#splitter` css. That only takes the css of the class at startup. Can something be done about this?

```
.splitterbar {
      --vaadin-split-layout-splitter: {
        background: var(--paper-indigo-500);
      };
}
.nosplit {
  --vaadin-split-layout-splitter: {
        visibility: hidden;
  };
}

<vaadin-split-layout class="splitterbar">
  <div class="textcontent">View 1</div>
  <div class="textcontent">View 2</div>
</vaadin-split-layout>
```

**Comment by platosha** [comment]
This is, probably, due to limitations of Polymer’s CSS mixin implementation. Mixins are not applied dynamically.

Please try to call `splitLayout.updateStyles()` in the JS after swapping the classes.

**Comment by limonte** [comment]
@platosha Should we add the mixin for the active state of splitter when it's clicked? E.g. `--vaadin-split-layout-splitter-active`? 

@SamaneriVimala will that mixin solve your issue?

**Comment by SamaneriVimala** [comment]
Thanks! The `updateStyles()` function worked. Not sure if an extra mixin would be necessary, but it might be something to consider if more people have this issue.

**Comment by platosha** [comment]
@limonte Not sure, the active state was not designed. But, as I see, there is a need in a property that hides the splitter. For example, to hide the splitter when one of the content areas is hidden.

**Comment by platosha** [comment]
Described the `splitterHidden` property proposal in #62
