### ISSUE TITLE
`splitterHidden` property

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-split-layout#62]
### Use Case

There is a layout, where one of two content elements is optionally hidden.

When one of the content elements is hidden, resizing the split is not applicable anymore, the splitter and the split layout functions become unnecessary. In this case, it is expected that the splitter is hidden.

### Suggested Solution

Add `splitterHidden: Boolean` property, false by default. When true, the splitter is hidden.

### Usage Example

Users can hide one of the content elements and the splitter at the same time by using bindings in a parent scope:

```html
<vaadin-split-layout splitter-hidden="[[_descriptionHidden]]">
  <div id="main"></div>
  <div id="description" hidden="[[_descriptionHidden]]">
</vaadin-split-layout>
```

**Comment by jouni** [comment]
I suspect this use case can easily be covered once we add the new theming/styling support for split layout as well. Then you should be able to easily target the splitter element and hide it by toggling a host attribute/class, like proposed here.

**Comment by manolo** [comment]
@jouni could you elaborate a bit more, how theming can handle this out-of-the-box ? I don't see an easy way to bind the hidden property to the splitter part.

**Comment by jouni** [comment]
```css
:host([theme~="hide-splitter"]) [part="splitter"] {
  display: none;
}
```

Probably more clean actually to just have a property for this which is bound to the splitter element hidden attribute. I was just thinking this might be something we leave for the themes to handle, if they want to provide such a variation. Not sure if this needs to be part of the core API. I haven’t heard this request from the community.
