### ISSUE TITLE
style="width: 95%" doesn't work like expected

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-split-layout#67]
![](https://i.imgur.com/IGeCvLn.png)

Obviously, the right content is more than 5%.

Reproducible here: https://www.webcomponents.org/element/vaadin/vaadin-split-layout

(Chrome/Linux)

**Comment by platosha** [comment]
That’s CSS flexbox feature. Width rather means `flexBasis` here. Unless the explicit width is set, the content width takes effect.

Just add 5% width for the second child split, and you got it.
