### ISSUE TITLE
DX testing

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-split-layout#7]
Walk around and show people the code examples and ask if they are enough. Ask Leif at least.

**Comment by samiheikki** [comment]
Test plan: https://docs.google.com/a/vaadin.com/document/d/1kUrAp5hxB9_tCwESnSbyIYhgubTe03_qH6ilzebe1wk/edit?usp=sharing

**Comment by samiheikki** [comment]
Please review the plan and if seems OK put back to top of next column so we can then organize DX testing

**Comment by samiheikki** [comment]
Wait for #6 to be merged first and then add customisation task for these test cases.

**Comment by limonte** [comment]
#6 is the issue and can't be merged :) You probably mean wait for #19 to be merged.

**Comment by samiheikki** [comment]
Well wait for #6 to be resolved :)
