### ISSUE TITLE
Menu items not visible when it crosses vaadin split display 

### ISSUE THREAD

**Issue by karthik-hande** [vaadin/vaadin-split-layout#72]
When I have a dropdown menu inside vaadin split display and when the menu item is long it crosses the split display range.In that case, all the menu items which cross the vaadin split display will be hidden.
Is there any other solution so that we can display the menu at the top of vaadin split display.

code looks like below:

```html
<vaadin-split-layout vertical>
     <div>
          First layout content
          <paper-menu><!--code for menu list--></paper-menu>
    </div>
    <div>Second layout content</div>
  </vaadin-split-layout>
```

Screenshots:
Img1: Observe the red line where split display ends and blue color is a simple div 
![1](https://user-images.githubusercontent.com/26201980/26916622-b3ccdee6-4c48-11e7-9aa0-25bd7b771109.jpg)
Img2: Menu is hidden when it crosses the split display layout
![2](https://user-images.githubusercontent.com/26201980/26916626-b88b7258-4c48-11e7-81d5-4aa1328f5ea4.jpg)
Img3:
![3](https://user-images.githubusercontent.com/26201980/26916635-bdaec17c-4c48-11e7-9907-bb44c5098b1d.jpg)

**Comment by tomivirkki** [comment]
Hi @karthik-hande 
The `<vaadin-split-layout>` intentionally clips internal content (to avoid a wider split handle from overflowing). As `<paper-menu>`’s overlay is also an internal element (it's not moved outside for example under the body tag), it gets clipped also.

You can work around this by resetting transform for the split layout:
```
vaadin-split-layout {
  transform: none;
}
```

**Comment by karthik-hande** [comment]
Is there any other solution??because I have footer and split bar displays above the footer like this
![capture](https://user-images.githubusercontent.com/26201980/26921558-1216076e-4c5a-11e7-9206-d07c3f77c438.PNG)

**Comment by karthik-hande** [comment]
Is it possible to make paper menu or paper menu button to display at the top most layer? so I think that works for all scenarios! please suggest me

**Comment by tomivirkki** [comment]
As mentioned `<paper-menu>`’s (and other Paper Elements) overlay is internal inside the element’s own local DOM so the clipping issue always needs to be worked around by the app.

At Vaadin we’re currently working on a generic use overlay component that teleports directly under the body on open and thus doesn’t suffer from the clipping issue. Similar approach is already in use in the current version of `<vaadin-combo-box>`.

About the other issue: The split bar of `<vaadin-split-layout>` should never be higher than the element itself. Kind of strange that if flows over the footer like that. Is there some style leak perhaps that extends the split bar beyond the element height?

**Comment by web-padawan** [comment]
Closing in favor of #92 which describes the actual change (that would require a new major).
