### ISSUE TITLE
split layout can't be extended

### ISSUE THREAD

**Issue by UrsKipfer** [vaadin/vaadin-split-layout#77]
I tried to extend the element but then I get an Error/Warning.
    class MySplitLayout extends Vaadin.SplitLayoutElement {
      static get is() { return 'my-split-layout'; }
........

I get: Could not find style data in module named my-split-layout-default-theme

The problem seems to be the line 17 of themable-mixin because this.is is is now the name of my element.

**Comment by tomivirkki** [comment]
Thanks for reporting, fix in https://github.com/vaadin/vaadin-themable-mixin/pull/18
