### ISSUE TITLE
Styling for demo examples is missing

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-split-layout#79]
![image](https://user-images.githubusercontent.com/6059356/30699600-1cd722be-9f20-11e7-98f5-1dc90c3bea37.png)

Reproducible here: https://cdn.vaadin.com/vaadin-split-layout/3.0.0-alpha2/demo/split-layout-basic-demos

Previous release: https://cdn.vaadin.com/vaadin-split-layout/3.0.0-alpha1/demo/

**Comment by tomivirkki** [comment]
All styling demos were removed https://github.com/vaadin/components-team-tasks/issues/280#issuecomment-330435536
