### ISSUE TITLE
pointer events keep beeing removed

### ISSUE THREAD

**Issue by jogibear9988** [vaadin/vaadin-split-layout#81]
sometime the vaadin split layout keep the pointerevents removed from my controls.

I think this can happen, if the notifyResize throws an exception!

Can you surround this with a try catch?

**Comment by limonte** [comment]
I believe this is the same as https://github.com/vaadin/vaadin-split-layout/issues/80

**Comment by manolo** [comment]
@jogibear9988 could you verify it it's the same problem that @limonte points out?

**Comment by limonte** [comment]
It is :) Fix is coming soon.

**Comment by limonte** [comment]
Fixed in [v3.0.1](https://github.com/vaadin/vaadin-split-layout/releases/tag/v3.0.1), thanks for reporting!
